import { StudentAttrs } from '@/models/student.model';

export default [
  {
    firstName: 'Ali',
    lastName: 'Khan',
    nationalCode: '9876543210',
    phoneNumber: '9876543210',
    fatherName: 'Ahmad',
    schoolName: 'ABC School',
    educationalLevel: 'Middle School',
  },
  {
    firstName: 'Sara',
    lastName: 'Johnson',
    nationalCode: '1234567890',
    phoneNumber: '1234567890',
    fatherName: 'Robert',
    schoolName: 'XYZ School',
    educationalLevel: 'High School',
  },
  {
    firstName: 'Mohammad',
    lastName: 'Smith',
    nationalCode: '1357924680',
    phoneNumber: '1357924680',
    fatherName: 'John',
    schoolName: 'PQR School',
    educationalLevel: 'University',
  },
  {
    firstName: 'Maryam',
    lastName: 'Anderson',
    nationalCode: '0246897531',
    phoneNumber: '0246897531',
    fatherName: 'Michael',
    schoolName: 'ABC School',
    educationalLevel: 'Middle School',
  },
  {
    firstName: 'Hassan',
    lastName: 'Williams',
    nationalCode: '2468135790',
    phoneNumber: '2468135790',
    fatherName: 'David',
    schoolName: 'XYZ School',
    educationalLevel: 'High School',
  },
  {
    firstName: 'Neda',
    lastName: 'Brown',
    nationalCode: '9876543211',
    phoneNumber: '9876543210',
    fatherName: 'Ahmad',
    schoolName: 'PQR School',
    educationalLevel: 'University',
  },
  {
    firstName: 'Amir',
    lastName: 'Davis',
    nationalCode: '1234567891',
    phoneNumber: '1234567890',
    fatherName: 'Robert',
    schoolName: 'ABC School',
    educationalLevel: 'Middle School',
  },
  {
    firstName: 'Zahra',
    lastName: 'Smith',
    nationalCode: '1357924681',
    phoneNumber: '1357924680',
    fatherName: 'John',
    schoolName: 'XYZ School',
    educationalLevel: 'High School',
  },
  {
    firstName: 'Reza',
    lastName: 'Johnson',
    nationalCode: '0246897532',
    phoneNumber: '0246897531',
    fatherName: 'Michael',
    schoolName: 'PQR School',
    educationalLevel: 'University',
  },
  {
    firstName: 'Fateme',
    lastName: 'Williams',
    nationalCode: '2468135791',
    phoneNumber: '2468135790',
    fatherName: 'David',
    schoolName: 'ABC School',
    educationalLevel: 'Middle School',
  },
  {
    firstName: 'Khosrow',
    lastName: 'Brown',
    nationalCode: '9876543212',
    phoneNumber: '9876543210',
    fatherName: 'Ahmad',
    schoolName: 'XYZ School',
    educationalLevel: 'High School',
  },
  {
    firstName: 'Laleh',
    lastName: 'Davis',
    nationalCode: '1234567892',
    phoneNumber: '1234567890',
    fatherName: 'Robert',
    schoolName: 'PQR School',
    educationalLevel: 'University',
  },
  {
    firstName: 'Hamed',
    lastName: 'Smith',
    nationalCode: '1357924682',
    phoneNumber: '1357924680',
    fatherName: 'John',
    schoolName: 'ABC School',
    educationalLevel: 'Middle School',
  },
  {
    firstName: 'Shadi',
    lastName: 'Williams',
    nationalCode: '0246897533',
    phoneNumber: '0246897531',
    fatherName: 'Michael',
    schoolName: 'XYZ School',
    educationalLevel: 'High School',
  },
  {
    firstName: 'Mehran',
    lastName: 'Brown',
    nationalCode: '2468135792',
    phoneNumber: '2468135790',
    fatherName: 'David',
    schoolName: 'PQR School',
    educationalLevel: 'University',
  },
  {
    firstName: 'Nazanin',
    lastName: 'Johnson',
    nationalCode: '9876543213',
    phoneNumber: '9876543210',
    fatherName: 'Ahmad',
    schoolName: 'ABC School',
    educationalLevel: 'Middle School',
  },
  {
    firstName: 'Armin',
    lastName: 'Davis',
    nationalCode: '1234567893',
    phoneNumber: '1234567890',
    fatherName: 'Robert',
    schoolName: 'XYZ School',
    educationalLevel: 'High School',
  },
  {
    firstName: 'Parisa',
    lastName: 'Smith',
    nationalCode: '1357924683',
    phoneNumber: '1357924680',
    fatherName: 'John',
    schoolName: 'PQR School',
    educationalLevel: 'University',
  },
  {
    firstName: 'Behzad',
    lastName: 'Williams',
    nationalCode: '0246897535',
    phoneNumber: '0246897531',
    fatherName: 'Michael',
    schoolName: 'ABC School',
    educationalLevel: 'Middle School',
  },
  {
    firstName: 'Mina',
    lastName: 'Brown',
    nationalCode: '2468135793',
    phoneNumber: '2468135790',
    fatherName: 'David',
    schoolName: 'XYZ School',
    educationalLevel: 'High School',
  },
  {
    firstName: 'Navid',
    lastName: 'Davis',
    nationalCode: '9876543214',
    phoneNumber: '9876543210',
    fatherName: 'Ahmad',
    schoolName: 'PQR School',
    educationalLevel: 'University',
  },
] as StudentAttrs[];
